github: [Paracetamol56] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: paracetamol56 # Replace with a single Patreon username
custom: ['https://www.turbosquid.com/fr/3d-models/3d-low-poly-airplanes-set-model-1827451']# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
