name: Format Scripts

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Unity Auto Format
        uses: tyirvine/Unity-Actions-Autoformat@v1.0.5
        with:
          path: 'Projet prod'/Assets/Scripts/
